### PR TITLE
#170766074 Integrating TravisCi and adding Badge in README file

### PR DESCRIPTION
**Pull request by manzi-guev**
### What does this PR do?
- It enables the integration of Travis to work
### Description of the task to be completed?
- Integrating TravisCI
- Adding the TravisCI badge in the README file
### What are the relevant pivotal tracker stories?
[#170766074](https://www.pivotaltracker.com/story/show/170766074)

### CODE REVIEW

**Review by karengir — DISMISSED** [review]
Good work!

**Review by jajajaden01 — DISMISSED** [review]
Looks good

**Comment by manzi-guev** [comment]
The reason why the tests are not passing its because the are no tests files. This is the first push, so definitely it will fail.

**Review by KKDoddy — APPROVED** [review]

**Review by karengir — APPROVED** [review]

**Review by YankyJayChris — APPROVED** [review]

**Review by jajajaden01 — APPROVED** [review]
Good Job

**Review by Nigorjeanluc — APPROVED** [review]

**Pull request merged**
