### PR TITLE
#170766073 setup of hound file

### PR DESCRIPTION
**Pull request by YankyJayChris**
#### What does this PR do?
setup of hound file

#### Description of Task to be completed?
 - Create the `.hound.yml` file

#### How should this be manually tested?
You can pull the `develop` or `ch-setup-HoundCI-170766073` branch and run this command `npm install`

#### Any background context you want to provide?
Useful links below
 - [Hound documentation](https://houndci.herokuapp.com/configuration#javascript)

#### What are the relevant pivotal tracker stories?
[#170766073](https://www.pivotaltracker.com/story/show/170766073)

### CODE REVIEW

**Review by jajajaden01 — DISMISSED** [review]
Good work

**Review by Nigorjeanluc — DISMISSED** [review]

**Review by KKDoddy — DISMISSED** [review]
Did you find a way to allow es6 codes?
There's another solution I had found where you add the following lines in <em>.hound.yml</em> file, but it only ignores the language style.

>javascript:
  enabled: false

**Review by key-joshua — CHANGES_REQUESTED** [review]
Hey Christian, may you resolve the conflict

Conflicting files
.gitignore
README.md
package-lock.json
package.json

**Review by karengir — APPROVED** [review]

**Review by key-joshua — APPROVED** [review]
Now it looks resolved

**Review by jajajaden01 — APPROVED** [review]

**Pull request merged**
