### PR TITLE
#170766076 setup dotenv file

### PR DESCRIPTION
**Pull request by YankyJayChris**
#### What does this PR do?
setup of dotenv file

#### Description of Task to be completed?
 - install dotenv dependencies
 - Create the `.env` file

#### How should this be manually tested?
You can pull the `develop` or `ch-setup-dotenv-170766076` branch and run this command `npm install`

#### Any background context you want to provide?
Useful links below
 - [npm dotenv](https://www.npmjs.com/package/dotenv)

#### What are the relevant pivotal tracker stories?
[#170766076](https://www.pivotaltracker.com/story/show/170766076)

### CODE REVIEW

**Review by jajajaden01 — DISMISSED** [review]
Good work.

**Review by jajajaden01 — DISMISSED** [review]
Good configuration

**Review by karengir — DISMISSED** [review]

**Review by Nigorjeanluc — DISMISSED** [review]

**Review by jajajaden01 — DISMISSED** [review]

**Review by karengir — DISMISSED** [review]

**Review by key-joshua — COMMENTED** [review]
Good work man

**Review by key-joshua — DISMISSED** [review]

**Review by jajajaden01 — DISMISSED** [review]

**Review by key-joshua — DISMISSED** [review]
Looks good now

**Review by jajajaden01 — DISMISSED** [review]

**Review by Nigorjeanluc — DISMISSED** [review]

**Review by izabayogit — DISMISSED** [review]

**Review by jajajaden01 — APPROVED** [review]

**Review by Nigorjeanluc — APPROVED** [review]

**Review by izabayogit — APPROVED** [review]

**Pull request merged**
